# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_streamUI(object):
    def setupUi(self, streamUI):
        streamUI.setObjectName("streamUI")
        streamUI.resize(829, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(streamUI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ip_LB_2 = QtWidgets.QLabel(streamUI)
        self.ip_LB_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ip_LB_2.setObjectName("ip_LB_2")
        self.horizontalLayout_3.addWidget(self.ip_LB_2)
        self.ip_LE_2 = QtWidgets.QLineEdit(streamUI)
        self.ip_LE_2.setText("")
        self.ip_LE_2.setObjectName("ip_LE_2")
        self.horizontalLayout_3.addWidget(self.ip_LE_2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ip_LB = QtWidgets.QLabel(streamUI)
        self.ip_LB.setAlignment(QtCore.Qt.AlignCenter)
        self.ip_LB.setObjectName("ip_LB")
        self.horizontalLayout_2.addWidget(self.ip_LB)
        self.ip_LE = QtWidgets.QLineEdit(streamUI)
        self.ip_LE.setText("")
        self.ip_LE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ip_LE.setObjectName("ip_LE")
        self.horizontalLayout_2.addWidget(self.ip_LE)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.link = QtWidgets.QPushButton(streamUI)
        self.link.setObjectName("link")
        self.verticalLayout.addWidget(self.link)
        self.web = QtWebEngineWidgets.QWebEngineView(streamUI)
        self.web.setUrl(QtCore.QUrl("https://xwxstudio.com/"))
        self.web.setObjectName("web")
        self.verticalLayout.addWidget(self.web)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(3, 16)

        self.retranslateUi(streamUI)
        QtCore.QMetaObject.connectSlotsByName(streamUI)

    def retranslateUi(self, streamUI):
        _translate = QtCore.QCoreApplication.translate
        streamUI.setWindowTitle(_translate("streamUI", "MyWidget"))
        self.ip_LB_2.setText(_translate("streamUI", "ip"))
        self.ip_LE_2.setPlaceholderText(_translate("streamUI", "<IP>"))
        self.ip_LB.setText(_translate("streamUI", "URL"))
        self.ip_LE.setPlaceholderText(_translate("streamUI", "http://<ip>:25565/stream.mjpg"))
        self.link.setText(_translate("streamUI", "Link Start"))
from PyQt5 import QtWebEngineWidgets
